/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    carreras: Carrera;
    posgrados: Posgrado;
    noticias: Noticia;
    categorias: Categoria;
    medios: Medio;
    documentos: Documento;
    facultades: Facultade;
    sedes: Sede;
    redirecciones: Redireccione;
    usuarios: Usuario;
    auditoria: Auditoria;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    carreras: CarrerasSelect<false> | CarrerasSelect<true>;
    posgrados: PosgradosSelect<false> | PosgradosSelect<true>;
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    medios: MediosSelect<false> | MediosSelect<true>;
    documentos: DocumentosSelect<false> | DocumentosSelect<true>;
    facultades: FacultadesSelect<false> | FacultadesSelect<true>;
    sedes: SedesSelect<false> | SedesSelect<true>;
    redirecciones: RedireccionesSelect<false> | RedireccionesSelect<true>;
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    auditoria: AuditoriaSelect<false> | AuditoriaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    configuracion: Configuracion;
  };
  globalsSelect: {
    configuracion: ConfiguracionSelect<false> | ConfiguracionSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Carreras de grado. Cada una se publica en uap.edu.py/{dirección-web}/.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carreras".
 */
export interface Carrera {
  id: number;
  nombre: string;
  /**
   * Para menús y tarjetas. Ej.: "Ing. en Informática".
   */
  nombreCorto?: string | null;
  facultad?: (number | null) | Facultade;
  /**
   * Ej.: "Licenciatura".
   */
  gradoAcademico?: string | null;
  tituloOtorgado?: string | null;
  /**
   * Ej.: "8 semestres", "5 meses".
   */
  duracion?: string | null;
  modalidad?: ('presencial' | 'virtual' | 'hibrida' | 'presencial_y_distancia') | null;
  /**
   * Ej.: "Nocturna", "Sábados".
   */
  jornada?: string | null;
  sedes?: (number | Sede)[] | null;
  /**
   * Texto de 1 o 2 oraciones para las tarjetas del listado (máx. 300 caracteres).
   */
  descripcionCorta?: string | null;
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  objetivo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  perfilIngreso?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  perfilEgreso?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  campoLaboral?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  requisitos?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Misión, visión, competencias u otra sección propia del programa.
   */
  seccionesAdicionales?:
    | {
        titulo: string;
        contenido: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Un elemento por semestre, en orden.
   */
  malla?:
    | {
        /**
         * Ej.: "1° Semestre".
         */
        nombre: string;
        asignaturas?:
          | {
              nombre: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  mallaPdf?: (number | null) | Documento;
  /**
   * Foto horizontal de al menos 1600 px de ancho.
   */
  imagenPrincipal?: (number | null) | Medio;
  galeria?: (number | Medio)[] | null;
  brochure?: (number | null) | Documento;
  documentos?: (number | Documento)[] | null;
  contacto?: {
    email?: string | null;
    telefono?: string | null;
    /**
     * Solo números, con código de país.
     */
    whatsapp?: string | null;
  };
  cta?: {
    /**
     * Ej.: "Solicita información".
     */
    texto?: string | null;
    url?: string | null;
  };
  /**
   * Código del formulario (ej.: inline/61/hi7fex). Vacío = el formulario general.
   */
  formularioBitrix?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Medio;
  };
  /**
   * Final de la URL, por ejemplo "psicologia" → uap.edu.py/psicologia/. Se completa sola a partir del nombre. Si la cambia en un contenido publicado, se crea una redirección automática.
   */
  slug: string;
  /**
   * Se cambia con los botones del panel "Flujo editorial".
   */
  estado?: ('borrador' | 'en_revision' | 'publicado' | 'no_publicado' | 'archivado') | null;
  /**
   * Menor número = aparece antes.
   */
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Agrupan las carreras (facultad) y los posgrados (área) en los listados y menús.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facultades".
 */
export interface Facultade {
  id: number;
  nombre: string;
  /**
   * Final de la URL, por ejemplo "psicologia" → uap.edu.py/psicologia/. Se completa sola a partir del nombre. Si la cambia en un contenido publicado, se crea una redirección automática.
   */
  slug: string;
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sedes".
 */
export interface Sede {
  id: number;
  nombre: string;
  direccion?: string | null;
  ciudad?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * PDF de hasta 30 MB. Para descargas rápidas en celular, apunte a menos de 10 MB.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos".
 */
export interface Documento {
  id: number;
  titulo: string;
  tipo: 'brochure' | 'malla' | 'reglamento' | 'otro';
  descripcion?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * JPG, PNG o WebP de hasta 10 MB. Se generan automáticamente versiones livianas para cada pantalla.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medios".
 */
export interface Medio {
  id: number;
  /**
   * Describa la imagen para personas que no pueden verla. Ej.: "Estudiantes en el laboratorio de odontología".
   */
  alt: string;
  credito?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    miniatura?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tarjeta?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Diplomados, especializaciones, maestrías y doctorados.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posgrados".
 */
export interface Posgrado {
  id: number;
  nombre: string;
  /**
   * Para menús y tarjetas. Ej.: "Ing. en Informática".
   */
  nombreCorto?: string | null;
  tipo: 'diplomado' | 'especializacion' | 'maestria' | 'doctorado' | 'maestria_doctorado' | 'otro';
  area?: (number | null) | Facultade;
  tituloOtorgado?: string | null;
  /**
   * Ej.: "8 semestres", "5 meses".
   */
  duracion?: string | null;
  modalidad?: ('presencial' | 'virtual' | 'hibrida' | 'presencial_y_distancia') | null;
  /**
   * Ej.: "Nocturna", "Sábados".
   */
  jornada?: string | null;
  sedes?: (number | Sede)[] | null;
  /**
   * Texto de 1 o 2 oraciones para las tarjetas del listado (máx. 300 caracteres).
   */
  descripcionCorta?: string | null;
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  objetivo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  objetivosEspecificos?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  dirigidoA?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  certificacion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  perfilIngreso?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  perfilEgreso?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  campoLaboral?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  requisitos?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Misión, visión, competencias u otra sección propia del programa.
   */
  seccionesAdicionales?:
    | {
        titulo: string;
        contenido: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Un elemento por módulo, en orden.
   */
  malla?:
    | {
        /**
         * Ej.: "1° Módulo".
         */
        nombre: string;
        asignaturas?:
          | {
              nombre: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  mallaPdf?: (number | null) | Documento;
  /**
   * Foto horizontal de al menos 1600 px de ancho.
   */
  imagenPrincipal?: (number | null) | Medio;
  galeria?: (number | Medio)[] | null;
  brochure?: (number | null) | Documento;
  documentos?: (number | Documento)[] | null;
  contacto?: {
    email?: string | null;
    telefono?: string | null;
    /**
     * Solo números, con código de país.
     */
    whatsapp?: string | null;
  };
  cta?: {
    /**
     * Ej.: "Solicita información".
     */
    texto?: string | null;
    url?: string | null;
  };
  /**
   * Código del formulario (ej.: inline/61/hi7fex). Vacío = el formulario general.
   */
  formularioBitrix?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Medio;
  };
  /**
   * Final de la URL, por ejemplo "psicologia" → uap.edu.py/psicologia/. Se completa sola a partir del nombre. Si la cambia en un contenido publicado, se crea una redirección automática.
   */
  slug: string;
  /**
   * Se cambia con los botones del panel "Flujo editorial".
   */
  estado?: ('borrador' | 'en_revision' | 'publicado' | 'no_publicado' | 'archivado') | null;
  /**
   * Menor número = aparece antes.
   */
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  titulo: string;
  /**
   * Resumen de 1 o 2 oraciones que aparece en el listado.
   */
  bajada?: string | null;
  imagenDestacada?: (number | null) | Medio;
  contenido?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  galeria?: (number | Medio)[] | null;
  /**
   * Nombre que se muestra. Vacío = "Comunicación UAP".
   */
  autor?: string | null;
  categoria?: (number | null) | Categoria;
  tags?: string[] | null;
  /**
   * Dirección en el WordPress anterior; se redirige a la nueva.
   */
  urlOriginal?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Medio;
  };
  /**
   * Final de la URL, por ejemplo "psicologia" → uap.edu.py/psicologia/. Se completa sola a partir del nombre. Si la cambia en un contenido publicado, se crea una redirección automática.
   */
  slug: string;
  /**
   * Si es futura, la noticia aprobada aparece sola en el sitio a esa hora.
   */
  fechaPublicacion: string;
  /**
   * Se cambia con los botones del panel "Flujo editorial".
   */
  estado?: ('borrador' | 'en_revision' | 'publicado' | 'no_publicado' | 'archivado') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  nombre: string;
  /**
   * Final de la URL, por ejemplo "psicologia" → uap.edu.py/psicologia/. Se completa sola a partir del nombre. Si la cambia en un contenido publicado, se crea una redirección automática.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Envía a los visitantes de una URL antigua a la nueva. Se crean solas al cambiar la dirección web de un contenido publicado.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirecciones".
 */
export interface Redireccione {
  id: number;
  /**
   * Solo la ruta, por ejemplo /contador-publico/
   */
  desde: string;
  tipo: '301' | '302' | '410';
  destinoTipo?: ('interno' | 'url') | null;
  destino?:
    | ({
        relationTo: 'carreras';
        value: number | Carrera;
      } | null)
    | ({
        relationTo: 'posgrados';
        value: number | Posgrado;
      } | null)
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null);
  /**
   * Ruta interna (/postgrados/) o URL completa (https://…).
   */
  url?: string | null;
  origen?: ('manual' | 'automatica' | 'migracion') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  nombre: string;
  /**
   * Los editores solo guardan borradores; Administrador y Super Admin publican.
   */
  roles: ('superadmin' | 'admin' | 'editor_carreras' | 'editor_posgrados' | 'editor_noticias' | 'lectura')[];
  /**
   * Desactivar en lugar de eliminar: conserva el historial y bloquea el acceso de inmediato.
   */
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'usuarios';
}
/**
 * Historial de cambios. Es de solo lectura: nadie puede editarlo ni borrarlo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditoria".
 */
export interface Auditoria {
  id: number;
  usuario?: (number | null) | Usuario;
  usuarioNombre?: string | null;
  usuarioEmail?: string | null;
  accion: 'creacion' | 'actualizacion' | 'cambio_estado' | 'eliminacion' | 'inicio_sesion' | 'transicion_rechazada';
  coleccion: string;
  documentoId: string;
  documentoTitulo?: string | null;
  campo?: string | null;
  valorAnterior?: string | null;
  valorNuevo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'carreras';
        value: number | Carrera;
      } | null)
    | ({
        relationTo: 'posgrados';
        value: number | Posgrado;
      } | null)
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'medios';
        value: number | Medio;
      } | null)
    | ({
        relationTo: 'documentos';
        value: number | Documento;
      } | null)
    | ({
        relationTo: 'facultades';
        value: number | Facultade;
      } | null)
    | ({
        relationTo: 'sedes';
        value: number | Sede;
      } | null)
    | ({
        relationTo: 'redirecciones';
        value: number | Redireccione;
      } | null)
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null)
    | ({
        relationTo: 'auditoria';
        value: number | Auditoria;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carreras_select".
 */
export interface CarrerasSelect<T extends boolean = true> {
  nombre?: T;
  nombreCorto?: T;
  facultad?: T;
  gradoAcademico?: T;
  tituloOtorgado?: T;
  duracion?: T;
  modalidad?: T;
  jornada?: T;
  sedes?: T;
  descripcionCorta?: T;
  descripcion?: T;
  objetivo?: T;
  perfilIngreso?: T;
  perfilEgreso?: T;
  campoLaboral?: T;
  requisitos?: T;
  seccionesAdicionales?:
    | T
    | {
        titulo?: T;
        contenido?: T;
        id?: T;
      };
  malla?:
    | T
    | {
        nombre?: T;
        asignaturas?:
          | T
          | {
              nombre?: T;
              id?: T;
            };
        id?: T;
      };
  mallaPdf?: T;
  imagenPrincipal?: T;
  galeria?: T;
  brochure?: T;
  documentos?: T;
  contacto?:
    | T
    | {
        email?: T;
        telefono?: T;
        whatsapp?: T;
      };
  cta?:
    | T
    | {
        texto?: T;
        url?: T;
      };
  formularioBitrix?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  estado?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posgrados_select".
 */
export interface PosgradosSelect<T extends boolean = true> {
  nombre?: T;
  nombreCorto?: T;
  tipo?: T;
  area?: T;
  tituloOtorgado?: T;
  duracion?: T;
  modalidad?: T;
  jornada?: T;
  sedes?: T;
  descripcionCorta?: T;
  descripcion?: T;
  objetivo?: T;
  objetivosEspecificos?: T;
  dirigidoA?: T;
  certificacion?: T;
  perfilIngreso?: T;
  perfilEgreso?: T;
  campoLaboral?: T;
  requisitos?: T;
  seccionesAdicionales?:
    | T
    | {
        titulo?: T;
        contenido?: T;
        id?: T;
      };
  malla?:
    | T
    | {
        nombre?: T;
        asignaturas?:
          | T
          | {
              nombre?: T;
              id?: T;
            };
        id?: T;
      };
  mallaPdf?: T;
  imagenPrincipal?: T;
  galeria?: T;
  brochure?: T;
  documentos?: T;
  contacto?:
    | T
    | {
        email?: T;
        telefono?: T;
        whatsapp?: T;
      };
  cta?:
    | T
    | {
        texto?: T;
        url?: T;
      };
  formularioBitrix?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  estado?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  titulo?: T;
  bajada?: T;
  imagenDestacada?: T;
  contenido?: T;
  galeria?: T;
  autor?: T;
  categoria?: T;
  tags?: T;
  urlOriginal?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  fechaPublicacion?: T;
  estado?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medios_select".
 */
export interface MediosSelect<T extends boolean = true> {
  alt?: T;
  credito?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        miniatura?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tarjeta?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos_select".
 */
export interface DocumentosSelect<T extends boolean = true> {
  titulo?: T;
  tipo?: T;
  descripcion?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facultades_select".
 */
export interface FacultadesSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sedes_select".
 */
export interface SedesSelect<T extends boolean = true> {
  nombre?: T;
  direccion?: T;
  ciudad?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirecciones_select".
 */
export interface RedireccionesSelect<T extends boolean = true> {
  desde?: T;
  tipo?: T;
  destinoTipo?: T;
  destino?: T;
  url?: T;
  origen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nombre?: T;
  roles?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditoria_select".
 */
export interface AuditoriaSelect<T extends boolean = true> {
  usuario?: T;
  usuarioNombre?: T;
  usuarioEmail?: T;
  accion?: T;
  coleccion?: T;
  documentoId?: T;
  documentoTitulo?: T;
  campo?: T;
  valorAnterior?: T;
  valorNuevo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Datos que aparecen en todo el sitio: contacto, redes, pie de página y SEO por defecto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracion".
 */
export interface Configuracion {
  id: number;
  telefono?: string | null;
  /**
   * Solo números con código de país. Ej.: 595981222785
   */
  whatsapp?: string | null;
  email?: string | null;
  direccion?: string | null;
  mapaUrl?: string | null;
  horario?: string | null;
  redes?: {
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    linkedin?: string | null;
  };
  campusVirtualUrl?: string | null;
  /**
   * Ej.: habilitación y acreditación. Confirme el texto con Secretaría General antes de publicarlo.
   */
  leyendaInstitucional?: string | null;
  seoTitulo?: string | null;
  seoDescripcion?: string | null;
  /**
   * 1200 × 630 px.
   */
  seoImagen?: (number | null) | Medio;
  /**
   * Ej.: inline/61/hi7fex
   */
  bitrixFormulario?: string | null;
  bitrixLoaderUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracion_select".
 */
export interface ConfiguracionSelect<T extends boolean = true> {
  telefono?: T;
  whatsapp?: T;
  email?: T;
  direccion?: T;
  mapaUrl?: T;
  horario?: T;
  redes?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
        linkedin?: T;
      };
  campusVirtualUrl?: T;
  leyendaInstitucional?: T;
  seoTitulo?: T;
  seoDescripcion?: T;
  seoImagen?: T;
  bitrixFormulario?: T;
  bitrixLoaderUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}